### ISSUE TITLE
When placed inside the SMA executable folder, SMALauncher.exe still downloads fresh build in game sub-folder

### ISSUE THREAD

**Issue by hsandt** [Leo40Git/SMALauncher#1]
If you download and run SMALauncher.exe, it will download the latest build (or rolling build with -R option) into a game subfolder. If this subfolder already exists, then it will upgrade any existing version of the editor, if needed.

However, I noticed that the SMA distribution itself contains a copy SMALauncher.exe along the editor (Shang_Mu_Architect_(version).exe), whether downloaded manually or via SMALauncher.exe itself, in which case we have a duplicate.

However, the embedded SMALauncher.exe doesn't work as expected: when run, it will create its own game subfolder inside the current working directory. In most cases, users are running the exe directly from the directory it is located in, which means the editor directory (the one containing (Shang_Mu_Architect_(version).exe)).

Therefore, instead of upgrading the existing editor exe there, it will create a new game subfolder with its own editor and SMALauncher exe. Rerunning SMALauncher.exe inside that game subfolder will repeat the process, causing endless folder recursion...

SMALauncher.exe should probably detect if the current working directory contains Shang_Mu_Architect_(version).exe (doing the same check as it does with a game subfolder) and upgrade that one if so.

Otherwise, the user must make sure to either always use the SMALauncher.exe in the parent directory, or at least open a terminal in the parent directory, then run game/SMALauncher.exe... But most users probably prefer just double-clicking on SMALauncher.exe, which doesn't allow to tune the current working directory.

**Comment by Leo40Git** [comment]
Oh right I completely forgot about this
The launcher isn't actually supposed to be distributed with the game, the idea is you should download the launcher _instead_ of downloading the game, and have the launcher automatically download the game for you.
I'll go tell Libbie to remove SMALauncher from the game archive.

**Comment by Leo40Git** [comment]
SMALauncher won't be distributed with SMA anymore, so... problem solved!

**Comment by hsandt** [comment]
OK, nice!
